// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGen.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\Dimuthu.D\source\repos\CodeGen\CodeGen\Templates\CBProductController.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class CBProductController : CBProductControllerBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write(@"
Using AutoMapper;
Using Commerce.Adapters.CitybreakAdapter.Controllers.DTO;
Using Commerce.Adapters.CitybreakAdapter.Infrastructure;
Using Commerce.Adapters.CitybreakAdapter.Model.AntiCorruptionLayer.Interfaces;
Using Commerce.Adapters.CitybreakAdapter.Model.Commerce.Config;
Using Commerce.Adapters.CitybreakAdapter.Model.Commerce.Error;
Using Commerce.Adapters.CitybreakAdapter.Model.Commerce.Helpers;
Using Commerce.Adapters.CitybreakAdapter.Model.Commerce.Requests;
Using Commerce.Adapters.CitybreakAdapter.Model.Commerce.Responses;
Using Microsoft.AspNetCore.Mvc;
Using Newtonsoft.Json;
Using Swashbuckle.AspNetCore.Annotations;


Namespace Commerce.Adapters.CitybreakAdapter.Controllers
{
    [Route(""v0/Adapter"")]
    [ApiController]
    Public Class CitybreakProductController :  ControllerBase
    {
        Private ReadOnly IMapper mapper;
        Private ReadOnly ILogger<CitybreakProductController> logger;
        Private ReadOnly IProductService productService;

        Public CitybreakProductController(IProductService productService, ILogger<CitybreakProductController> logger, IMapper mapper)
        {
            this.logger = logger ?? throw New ArgumentNullException(NameOf(logger));
            this.productService = productService ?? throw New ArgumentNullException(NameOf(productService));
            this.mapper = mapper ?? throw New ArgumentNullException(NameOf(mapper));
        }
		
		");
            
            #line 38 "C:\Users\Dimuthu.D\source\repos\CodeGen\CodeGen\Templates\CBProductController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EndpointsCode));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n\r\n        /// <summary>\r\n        /// Creates ProductServiceMessage based on S" +
                    "erviceMessage, AdapterConfig And AuthorizationConfig. \r\n        /// </summary>\r\n" +
                    "        /// <param name=\"serviceMessage\">Adapter service message object. <see cr" +
                    "ef=\"ServiceMessage\"/></param>\r\n        /// <param name=\"config\">Adapter configur" +
                    "ation object. <see cref=\"AdapterConfig\"/></param>\r\n        /// <param name=\"auth" +
                    "orizationConfig\">Authorization configuration object. <see cref=\"AuthorizationCon" +
                    "fig\"/></param>\r\n        /// <returns><see cref=\"ProductServiceMessage\"/></return" +
                    "s>\r\n        /// <exception cref=\"ArgumentNullException\"></exception>\r\n        Pr" +
                    "ivate ProductServiceMessage CreateProductServiceMessage(ServiceMessage serviceMe" +
                    "ssage, AdapterConfig config, AuthorizationConfig authorizationConfig)\r\n        {" +
                    "\r\n            If (serviceMessage == null)\r\n        Throw New ArgumentNullExcepti" +
                    "on(NameOf(serviceMessage));\r\n            If (String.IsNullOrEmpty(serviceMessage" +
                    ".Payload))\r\n        Throw New ArgumentNullException(NameOf(serviceMessage.Payloa" +
                    "d));\r\n            If (authorizationConfig == null)\r\n        Throw New ArgumentNu" +
                    "llException(NameOf(authorizationConfig));\r\n            If (!(config.HttpEndpoint" +
                    "s?.Any() ?? True))\r\n        Throw New ArgumentNullException(NameOf(config.HttpEn" +
                    "dpoints));\r\n\r\n            // We may need multiple addresses, so they have to be " +
                    "sent in HttpEndpoints.\r\n            ProductServiceConfig serviceConfig = New Pro" +
                    "ductServiceConfig\r\n            {\r\n                HttpEndpoints = config.HttpEnd" +
                    "points.ToList()\r\n            };\r\n\r\n            // Deserialize the base message f" +
                    "rom the payload JSON.\r\n            ProductServiceMessage? message = JsonConvert." +
                    "DeserializeObject<ProductServiceMessage>(serviceMessage.Payload);\r\n\r\n           " +
                    " If (message == null)\r\n        Throw New Exception(\"Deserialization of product s" +
                    "ervice message failed.\");\r\n\r\n            // Set the config objects.\r\n           " +
                    " message.ServiceConfig = serviceConfig;\r\n            message.AuthorizationConfig" +
                    " = authorizationConfig;\r\n\r\n            Return message;\r\n        }\r\n    }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class CBProductControllerBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        public System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
